steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/txtai', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/txtai']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'txtai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/txtai'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--vpc-connector'
      - 'aurite-vpc-connector'
      - '--service-account'
      - 'txtai-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/txtai'

options:
  logging: CLOUD_LOGGING_ONLY
