# Allow indexing of documents
writable: True

# Authentication configuration
api:
  key: ${API_KEY}
  health:
    enabled: true
    auth: false # Allow health checks without auth

# Embeddings configuration
embeddings:
  path: sentence-transformers/all-MiniLM-L6-v2
  device: cpu

# Index configuration
index:
  path: gs://aurite-txtai-dev/index
  backend: annoy

# Text segmentation for chunking documents
segmentation:
  sentences: true
